apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::637423512359:role/GitHubAction-AssumeRoleWithAction
      username: github-ci
      groups:
        - system:masters